PROTOCOLS=com.jctal.land.das.domain.Protocol
INSTRUMENTS=com.jctal.land.das.domain.Instrument
DEVICE_PARAMETERS=com.jctal.land.das.domain.DeviceParameter
DEVICES=com.jctal.land.das.domain.Device
ACCESS_METHODS=com.jctal.land.das.domain.AccessMethod
