# Sample ResourceBundle properties file
PROJECTS=com.jctal.land.das.domain.project.Project
DATA_TABLE=com.jctal.land.das.domain.project.DataTable
GRAPHS=com.jctal.land.das.domain.project.Graph
NOTES=com.jctal.land.das.domain.project.Note
SAMPLE_SCHEME=com.jctal.land.das.domain.project.SampleScheme
SETPOINTS=com.jctal.land.das.domain.project.Setpoint
TABLE_PARTS=com.jctal.land.das.domain.project.TablePart
INST_PANELS=com.jctal.land.das.domain.project.InstPanel
