"use client";
import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { createParty, findPartyDuplicates } from "@/lib/m34/crm-actions";
import { PARTY_ROLES } from "@/lib/m34/crm";
import type { M34PartyRoleType, M34PartyType } from "@/generated/prisma/enums";
const input="mt-1 w-full rounded-lg border border-border-strong bg-canvas px-3 py-2 text-ink";
export default function NewPartyForm(){const router=useRouter();const[busy,start]=useTransition();const[error,setError]=useState("");const[candidates,setCandidates]=useState<{id:string;code:string;legalName:string;taxId:string|null;status:string}[]>([]);const[roles,setRoles]=useState<M34PartyRoleType[]>(["CUSTOMER"]);const[type,setType]=useState<M34PartyType>("ORGANIZATION");
function toggle(v:M34PartyRoleType){setRoles(x=>x.includes(v)?x.filter(i=>i!==v):[...x,v])}
return <form className="flex flex-col gap-5" onSubmit={e=>{e.preventDefault();setError("");const f=new FormData(e.currentTarget);start(async()=>{const r=await createParty({partyType:type,legalName:String(f.get("legalName")||""),shortName:String(f.get("shortName")||""),taxId:String(f.get("taxId")||""),legacyCode:String(f.get("legacyCode")||""),address:String(f.get("address")||""),ward:String(f.get("ward")||""),province:String(f.get("province")||""),source:String(f.get("source")||""),roles,contactName:String(f.get("contactName")||""),contactPosition:String(f.get("contactPosition")||""),contactEmail:String(f.get("contactEmail")||""),contactPhone:String(f.get("contactPhone")||""),contactIsLegalRep:f.get("contactIsLegalRep")==="on"});if(r.ok)router.push(`/modules/M34/crm/${r.id}`);else setError(r.message)})}}>
<section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-head text-base font-bold text-ink">1. Định danh chủ thể</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-ink">Loại chủ thể *<select value={type} onChange={e=>setType(e.target.value as M34PartyType)} className={input}><option value="ORGANIZATION">Tổ chức/Doanh nghiệp</option><option value="PERSON">Cá nhân</option></select></label><label className="text-sm font-medium text-ink">Tên pháp lý/Họ tên *<input name="legalName" required className={input}/></label><label className="text-sm font-medium text-ink">Mã số thuế/Định danh {type==="ORGANIZATION"&&"*"}<input name="taxId" required={type==="ORGANIZATION"} className={input}/></label><label className="text-sm font-medium text-ink">Tên viết tắt<input name="shortName" className={input}/></label><label className="text-sm font-medium text-ink">Mã khách hàng cũ<input name="legacyCode" className={input}/></label><label className="text-sm font-medium text-ink">Nguồn khách hàng<input name="source" className={input}/></label></div><button type="button" className="mt-4 rounded-lg border border-border-strong px-3 py-2 text-sm font-semibold text-ink hover:bg-sunk" onClick={()=>{const form=document.querySelector("form") as HTMLFormElement;const f=new FormData(form);start(async()=>setCandidates(await findPartyDuplicates(String(f.get("legalName")||""),String(f.get("taxId")||""))))}}>Kiểm tra trùng</button>{candidates.length>0&&<div className="mt-3 rounded-lg border border-warn/40 bg-warn-soft p-3 text-sm"><strong>Hồ sơ có thể trùng:</strong>{candidates.map(c=><a key={c.id} href={`/modules/M34/crm/${c.id}`} className="mt-1 block text-accent underline">{c.code} · {c.legalName} · {c.taxId||"không MST"}</a>)}</div>}</section>
<section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-head text-base font-bold text-ink">2. Vai trò nghiệp vụ *</h2><div className="mt-3 grid gap-2 sm:grid-cols-2">{PARTY_ROLES.map(([v,l])=><label key={v} className="flex items-center gap-2 rounded-lg border border-border p-3 text-sm text-ink"><input type="checkbox" checked={roles.includes(v)} onChange={()=>toggle(v)}/>{l}</label>)}</div></section>
<section className="rounded-xl border border-border bg-surface p-5"><h2 className="font-head text-base font-bold text-ink">3. Địa chỉ và đầu mối</h2><div className="mt-4 grid gap-4 md:grid-cols-2"><label className="text-sm font-medium text-ink md:col-span-2">Địa chỉ<input name="address" className={input}/></label><label className="text-sm font-medium text-ink">Phường/Xã<input name="ward" className={input}/></label><label className="text-sm font-medium text-ink">Tỉnh/Thành phố<input name="province" className={input}/></label><label className="text-sm font-medium text-ink">Họ tên đầu mối<input name="contactName" className={input}/></label><label className="text-sm font-medium text-ink">Chức vụ<input name="contactPosition" className={input}/></label><label className="text-sm font-medium text-ink">Email<input name="contactEmail" type="email" className={input}/></label><label className="text-sm font-medium text-ink">Điện thoại<input name="contactPhone" className={input}/></label><label className="flex items-center gap-2 text-sm text-ink md:col-span-2"><input name="contactIsLegalRep" type="checkbox"/>Đây là người đại diện pháp luật</label></div></section>
{error&&<p role="alert" className="rounded-lg border border-crit/40 bg-crit-soft p-3 text-sm text-crit">{error}</p>}<div className="flex justify-end"><button disabled={busy} className="rounded-lg bg-accent px-5 py-2.5 text-sm font-semibold text-accent-ink disabled:opacity-50">{busy?"Đang lưu…":"Lưu hồ sơ Nháp"}</button></div></form>}
