// Danh mục Phương tiện đo (PTĐ) — dữ liệu nhúng tĩnh, port nguyên văn từ mảng `CATALOG`
// trong 08_Source/index.html (150 dòng mẫu). ĐÂY KHÔNG PHẢI DỮ LIỆU SỐNG: bản gốc gọi
// `GET /api/phuong-tien-do` (ManLab thật, chưa tồn tại) và luôn fallback về mảng nhúng này
// khi không gọi được — M05_ThietBi (module quản lý danh mục PTĐ) cũng chưa có backend thật
// trong aios-platform, nên increment này giữ nguyên hành vi fallback, KHÔNG giả vờ có dữ liệu
// sống (xem spec.md Quyết định phạm vi #1).
export interface CatalogItem {
  ten: string;
  tenTA: string;
  linhVuc: string;
  dichVu: string; // "HC" (hiệu chuẩn) | "KĐ" (kiểm định) | "TN" (thử nghiệm)
  phamVi: string;
  mpelod: string;
  cmcMax: number;
  cmcDvt: string;
  quyTrinh: string;
  nangLucCode: string;
  trangThaiPTD: string; // "Đã duyệt" | "ĐN LĐV duyệt" | "ĐN LĐP duyệt"
}

export const CATALOG: CatalogItem[] = [
  {
    "ten": "Máy khuấy",
    "tenTA": "Stirrer meter",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 99999) rpm",
    "mpelod": "±2 %",
    "cmcMax": 0.08,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCS 02 (Máy đo tốc độ vòng quay - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "Đã duyệt"
  },
  {
    "ten": "Bếp gia nhiệt",
    "tenTA": "Heating stove",
    "linhVuc": "Nhiệt độ",
    "dichVu": "HC",
    "phamVi": "(50 ÷ 450) °C",
    "mpelod": "0,5 °C",
    "cmcMax": 1.1,
    "cmcDvt": "°C",
    "quyTrinh": "ETV.MCT 02 (Thiết bị phá mẫu COD và thiết bị tương tự - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "Đã duyệt"
  },
  {
    "ten": "Tủ ủ BOD",
    "tenTA": "BOD chamber",
    "linhVuc": "Nhiệt độ",
    "dichVu": "HC",
    "phamVi": "(40 ÷ 450) °C",
    "mpelod": "± 0,5 °C",
    "cmcMax": 0.78,
    "cmcDvt": "°C",
    "quyTrinh": "ETV.MCT 01 (Tủ nhiệt - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "Đã duyệt"
  },
  {
    "ten": "Tủ an toàn sinh học",
    "tenTA": "Biosafety Cabinet",
    "linhVuc": "Cơ học",
    "dichVu": "TN",
    "phamVi": "(0.01 ÷ 5) m/s",
    "mpelod": "5 %",
    "cmcMax": 0.3,
    "cmcDvt": "m/s",
    "quyTrinh": "ETV.MTMe 01 (Tủ an toàn sinh học - Quy trình nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "Đã duyệt"
  },
  {
    "ten": "Cân phân tích",
    "tenTA": "Analytical balance",
    "linhVuc": "Khối lượng",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 600) g",
    "mpelod": "",
    "cmcMax": 0.0031,
    "cmcDvt": "g",
    "quyTrinh": "ETV.MCM 01 (Cân phân tích và cân kỹ thuật - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "Đã duyệt"
  },
  {
    "ten": "Kính hiển vi",
    "tenTA": "Microscope",
    "linhVuc": "Quang học",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) Gói",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "Gói",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "Đã duyệt"
  },
  {
    "ten": "Phương tiện đo Tổng Phốt pho (TP) - Trạm nước",
    "tenTA": "TP",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 1000) mg/L",
    "mpelod": "±5 %",
    "cmcMax": 1.5,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MVW 08 (Phương tiện đo nồng độ các chất trong nước -  Quy trình kiểm định nhóm 1)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí HCl- Cầm tay",
    "tenTA": "Gas analyzers of HCl in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0.12) %V",
    "mpelod": "±4 %",
    "cmcMax": 1.1,
    "cmcDvt": "%V",
    "quyTrinh": "ETV.MCA 02 (Phương tiện đo nồng độ các khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí NO2 (**)",
    "tenTA": "Gas analyzers of NO2",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 0.05) %V",
    "mpelod": "±5 %",
    "cmcMax": 2.1,
    "cmcDvt": "%V",
    "quyTrinh": "ĐLVN 265:2016 (Phương tiện đo nồng độ SO2, CO2, CO, NOx trong không khí - Quy trình kiểm định nhóm 1)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ ôxy hòa tan",
    "tenTA": "Dissolved oxygen meters",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 20) mg/L",
    "mpelod": "",
    "cmcMax": 2.1,
    "cmcDvt": "mg/L",
    "quyTrinh": "ĐLVN 276 : 2014 (Phương tiện đo nồng độ ôxy hòa tan - Quy trình kiểm định)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo BOD - Trạm nước",
    "tenTA": "BOD measuring equipment - Water station",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 0) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "NTP (KĐ) (Quy trình kiểm định - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo Coliform",
    "tenTA": "Coliform Analyser",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo Nitrit - Trạm nước",
    "tenTA": "Nitrit",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Thiết bị phân tích dòng liên tục",
    "tenTA": "Continuous flow analyzer",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Máy trộn vữa xi măng",
    "tenTA": "Cement mortar mixer",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 285) rpm",
    "mpelod": "±5",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Máy dằn tạo mẫu xi măng",
    "tenTA": "Cement model making machine",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 15) mm",
    "mpelod": "±0.5",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Máy kiểm tra tần số",
    "tenTA": "Frequency tester",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) Hz",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "Hz",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Máy quang phổ hồng ngoại (FT-IR)",
    "tenTA": "",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) cm",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "7; 9; 10;8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Chuẩn đo lưu lượng nước (dùng kiểm định máy chạy thận nhân tạo)",
    "tenTA": "Water Flow",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 2000) mL/min",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Vi khí hậu (Tốc độ gió)",
    "tenTA": "Microclimate (Wind Speed)",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) m/s",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "m/s",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Nhiệt kế điện trở Platin (PRT)",
    "tenTA": "Platinium Resistance Thermometer",
    "linhVuc": "Nhiệt độ",
    "dichVu": "HC",
    "phamVi": "(-200 ÷ 420) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo nhiệt trị",
    "tenTA": "Instrument for measuring calorific value",
    "linhVuc": "Nhiệt độ",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "°C",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Bể điều nhiệt",
    "tenTA": "Liquid Bath",
    "linhVuc": "Nhiệt độ",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 100) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "°C",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Thiết bị chỉ thị nhiệt độ hiện số",
    "tenTA": "Temperature indicators",
    "linhVuc": "Nhiệt độ",
    "dichVu": "HC",
    "phamVi": "(-100 ÷ 1600) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "°C",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Bộ chuẩn đa chức năng - Đo nhiệt độ",
    "tenTA": "Multifunctional calibration kit - Temperature measurement",
    "linhVuc": "Nhiệt độ",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 0) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "°C",
    "quyTrinh": "ĐLVN 160:2005 (Thiết bị chỉ thị nhiệt độ hiện số và tương tự - Quy trình hiệu chuẩn)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Áp kế nồi hấp tiệt trùng",
    "tenTA": "Autoclave Pressure Gauge",
    "linhVuc": "Áp suất",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 4) bar",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (KĐ) (Quy trình kiểm định - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Máy phân tích an toàn điện",
    "tenTA": "Electrical safety analyzer",
    "linhVuc": "Điện từ - Không điện",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 10) mA",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mA",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Bộ chuẩn đa chức năng - Phát nhiệt độ",
    "tenTA": "Multifunctional calibration unit - Temperature transmitter",
    "linhVuc": "Điện từ - Không điện",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "°C",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Hiệu chỉnh, thử nghiệm độ màu",
    "tenTA": "Calibrate and testing color",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 100) mg/L Pt/Co",
    "mpelod": "± mg/L Pt/Co",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTW 01 (Phương tiện đo hàm lượng các thông số trong nước - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Chất lượng nước sau lọc qua máy lọc nước (đo trực tiếp pH)",
    "tenTA": "Water quality after filtration through a water purifier (pH)",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 14) pH",
    "mpelod": "3 %",
    "cmcMax": 0,
    "cmcDvt": "pH",
    "quyTrinh": "ETV.MTW 04 (Chất lượng nước sau lọc qua máy lọc nước - Quy trình thử nghiệm)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Hiệu chỉnh, thử nghiệm NO3",
    "tenTA": "Calibration and testing NO3",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 1000) mg/L",
    "mpelod": "±0,1 mg/L",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "ETV.MTW 01 (Phương tiện đo hàm lượng các thông số trong nước - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo BOD",
    "tenTA": "BOD",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 0) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "NTP (TN) (Quy trình thử nghiệm - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Bảo dưỡng máy đo áp suất",
    "tenTA": "Pressure gauge maintenance",
    "linhVuc": "Áp suất",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mBar",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mBar",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Dụng cụ Vicat",
    "tenTA": "Vicat Tools",
    "linhVuc": "Độ dài",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 50) mm",
    "mpelod": "±0,01",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí",
    "tenTA": "Gas Analyzer",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 10000) ppm",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "ppm",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Hiệu chỉnh, thử nghiệm phương tiện đo áp suất",
    "tenTA": "Calibrate, test and apply the means",
    "linhVuc": "Giải ngân",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 0) Pa",
    "mpelod": "± bar",
    "cmcMax": 0,
    "cmcDvt": "Pa",
    "quyTrinh": "ETV. MTT 01 (Phương tiện đo nhiệt độ môi trường nước - Quy trình thử nghiệm)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Hiệu chỉnh, thử nghiệm phương tiện đo bụi",
    "tenTA": "Calibration and testing of dust measuring equipment",
    "linhVuc": "Giải ngân",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 0) ppm",
    "mpelod": "± mg/m³",
    "cmcMax": 0,
    "cmcDvt": "ppm",
    "quyTrinh": "ETV. MTT 01 (Phương tiện đo nhiệt độ môi trường nước - Quy trình thử nghiệm)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Hiệu chỉnh, thử nghiệm phương tiện đo gió",
    "tenTA": "Calibration and testing of wind measuring equipment",
    "linhVuc": "Giải ngân",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 14) m/s",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "m/s",
    "quyTrinh": "ETV.MTF 05 (Thiết bị đo tốc độ gió - Quy trình thử nghiệm)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Cân băng tải đến 5.000 t/h",
    "tenTA": "Conveyor-belt scales",
    "linhVuc": "Khối lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 5000) t/h",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "t/h",
    "quyTrinh": "NTP (KĐ) (Quy trình kiểm định - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Cân băng tải đến 10.000 t/h",
    "tenTA": "Conveyor-belt scales",
    "linhVuc": "Khối lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 10000) t/h",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "t/h",
    "quyTrinh": "NTP (KĐ) (Quy trình kiểm định - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Cân băng tải đến 15.000 t/h",
    "tenTA": "Conveyor-belt scales",
    "linhVuc": "Khối lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 15000) t/h",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "t/h",
    "quyTrinh": "NTP (KĐ) (Quy trình kiểm định - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện thử độ bền kéo nén",
    "tenTA": "Tensile and compression test equipment",
    "linhVuc": "Lực",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 3.05916e+008) kg",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Đồng hồ bấm giây",
    "tenTA": "Stopwatch",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 36000) s",
    "mpelod": "",
    "cmcMax": 0,
    "cmcDvt": "s",
    "quyTrinh": "ETV.MCS 06 (Đồng hồ bấm giây - Quy trình hiệu chuẩn)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Quả cân cấp chính xác M1 (1-20) kg",
    "tenTA": "Weights of classes M1 (1-20) kg",
    "linhVuc": "Khối lượng",
    "dichVu": "HC",
    "phamVi": "(1 ÷ 20) kg",
    "mpelod": "",
    "cmcMax": 0,
    "cmcDvt": "kg",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Cân bàn",
    "tenTA": "Platform scales",
    "linhVuc": "Khối lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 250) kg",
    "mpelod": "",
    "cmcMax": 0,
    "cmcDvt": "kg",
    "quyTrinh": "ĐLVN 14:2009 (Cân bàn - Quy trình Kiểm định)",
    "nangLucCode": "2;6;5",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Cân treo dọc thép –  lá đề",
    "tenTA": "Unequal level arm balances (Steel yards)",
    "linhVuc": "Khối lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 200) kg",
    "mpelod": "",
    "cmcMax": 0,
    "cmcDvt": "kg",
    "quyTrinh": "ĐLVN 02:2009 (Cân treo - Quy trình Kiểm định)",
    "nangLucCode": "2;6;1",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Cân đồng hồ lò xo",
    "tenTA": "Spring dial scales",
    "linhVuc": "Khối lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 200) kg",
    "mpelod": "",
    "cmcMax": 0,
    "cmcDvt": "kg",
    "quyTrinh": "ĐLVN 30:2019 (Cân đồng hồ lò xo - Quy trình Kiểm định)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Cân bàn < 100 kg",
    "tenTA": "Platform scales",
    "linhVuc": "Khối lượng",
    "dichVu": "HC",
    "phamVi": "",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐV duyệt"
  },
  {
    "ten": "Phương tiện đo Tổng chất rắn hòa tan (TDS)",
    "tenTA": "Total dissolved solids meter",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 200000) mg/L",
    "mpelod": "± 5 %",
    "cmcMax": 0.58,
    "cmcDvt": "%",
    "quyTrinh": "ĐLVN 80:2017 (Phương tiện đo tổng chất rắn hòa tan trong nước - Quy trình kiểm định)",
    "nangLucCode": "1;2;2",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Dung dịch chuẩn Độ đục (Turb)",
    "tenTA": "Turbidity standard solution",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 4000) NTU",
    "mpelod": "± 5 %",
    "cmcMax": 5.1,
    "cmcDvt": "%",
    "quyTrinh": "ĐLVN 278:2015 (Dung dịch chuẩn độ đục (Turb) - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Dung dịch chuẩn pH",
    "tenTA": "pH standard solution",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 14) pH",
    "mpelod": "± 5 %",
    "cmcMax": 0.1,
    "cmcDvt": "pH",
    "quyTrinh": "ĐLVN 280:2015 (Dung dịch chuẩn độ pH - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Nồng độ oxy hòa tan (DO)",
    "tenTA": "Dissolved oxygen meter",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 20) mg/L",
    "mpelod": "6 %",
    "cmcMax": 2.1,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCW 06 (Phương tiện đo ôxy hoà tan (DO) - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ dẫn điện (EC)",
    "tenTA": "Electrolytic conductivity meter",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 500) mS/cm",
    "mpelod": "± 5 %",
    "cmcMax": 0.63,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCW 02 (Phương tiện đo độ dẫn điện (EC) - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ muối",
    "tenTA": "Salinity meter",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 100) ‰",
    "mpelod": "±5 %",
    "cmcMax": 1.63,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCW 07 (Phương tiện đo độ muối, mặn - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Tốc độ vòng quay",
    "tenTA": "Rotational Speedometer of Equipment",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 99999) rpm",
    "mpelod": "2 %",
    "cmcMax": 0.58,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCS 02 (Máy đo tốc độ vòng quay - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Đồng hồ đo thể tích khí",
    "tenTA": "Gas gauge meter",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "HC",
    "phamVi": "(0 ~ 10) m³/h",
    "mpelod": "2 %",
    "cmcMax": 2.0,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCF 02 (Đồng hồ đo thể tích khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Tốc độ gió",
    "tenTA": "Anemometer",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 15) m/s",
    "mpelod": "±3 %",
    "cmcMax": 1.5,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCF 03 (Phương tiện đo vận tốc gió - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị thu mẫu khí lưu lượng thấp",
    "tenTA": "Air flow meter",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 70) L/min",
    "mpelod": "± 2 %",
    "cmcMax": 2.5,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCF 01 (Phương tiện đo lưu lượng khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Quang phổ tử ngoại khả kiến (UV-Vis)",
    "tenTA": "UV/Vis Spectrophotometer",
    "linhVuc": "Quang học",
    "dichVu": "HC",
    "phamVi": "(190 ÷ 900) nm",
    "mpelod": "± 2 %",
    "cmcMax": 0.22,
    "cmcDvt": "nm",
    "quyTrinh": "ETV.MCO 01 (Phương tiện đo quang phổ tử ngoại - khả kiến (UV-Vis) - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Máy so màu",
    "tenTA": "Spectrophotometer",
    "linhVuc": "Quang học",
    "dichVu": "HC",
    "phamVi": "(190 ÷ 1100) nm/ (0 ÷ 2) Abs",
    "mpelod": "± 2 %",
    "cmcMax": 0.22,
    "cmcDvt": "nm",
    "quyTrinh": "ETV.MCO 01 (Phương tiện đo quang phổ tử ngoại - khả kiến (UV-Vis) - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Nhiệt kế chỉ thị hiện số",
    "tenTA": "Digital thermometer",
    "linhVuc": "Nhiệt độ",
    "dichVu": "KĐ",
    "phamVi": "(-20 ÷ 1200) °C",
    "mpelod": "0,05-3 °C",
    "cmcMax": 0.62,
    "cmcDvt": "°C",
    "quyTrinh": "ĐLVN 138:2004 (Nhiệt kế chỉ thị hiện số và tương tự - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị chỉ thị nhiệt độ hiện số",
    "tenTA": "Temperature indicators",
    "linhVuc": "Nhiệt độ",
    "dichVu": "KĐ",
    "phamVi": "(-100 ÷ 1600) °C",
    "mpelod": "± (0,27 ~ 1,23) °C",
    "cmcMax": 1.0,
    "cmcDvt": "°C",
    "quyTrinh": "ĐLVN 160:2005 (Thiết bị chỉ thị nhiệt độ hiện số và tương tự - Quy trình hiệu chuẩn)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Nhiệt độ - Đa chỉ tiêu",
    "tenTA": "Thermometer",
    "linhVuc": "Nhiệt độ",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 120) °C",
    "mpelod": "±0.5 °C",
    "cmcMax": 0.18,
    "cmcDvt": "",
    "quyTrinh": "ĐLVN 138:2004 (Nhiệt kế chỉ thị hiện số và tương tự - Quy trình hiệu chuẩn)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Nhiệt độ không khí",
    "tenTA": "Thermometer in air",
    "linhVuc": "Nhiệt độ",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 50) °C",
    "mpelod": "± 0,5 °C",
    "cmcMax": 0.05,
    "cmcDvt": "°C",
    "quyTrinh": "ĐLVN 359:2019 (Phương tiện đo nhiệt độ/ độ ẩm không khí - Quy trình kiểm định)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "PTĐ nhiệt độ GSOT",
    "tenTA": "PTĐ nhiệt độ GSOT",
    "linhVuc": "Nhiệt độ",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 1000) °C",
    "mpelod": "2 %",
    "cmcMax": 2.0,
    "cmcDvt": "mg/L",
    "quyTrinh": "ĐLVN 01:GSOT (PTĐ Nhiệt độ GSOT - Quy trình kiểm định)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ ẩm",
    "tenTA": "Hygrometer",
    "linhVuc": "Độ ẩm",
    "dichVu": "HC",
    "phamVi": "(10 ÷ 98) %RH",
    "mpelod": "± 0,09 %RH",
    "cmcMax": 1.0,
    "cmcDvt": "%RH",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Vi khí hậu (Độ ẩm)",
    "tenTA": "Hygrometer",
    "linhVuc": "Độ ẩm",
    "dichVu": "HC",
    "phamVi": "(5 ÷ 95) %RH",
    "mpelod": "1 %RH",
    "cmcMax": 1.0,
    "cmcDvt": "%RH",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo độ ẩm - Trạm khí xung quanh",
    "tenTA": "Hygrometer in ambient air",
    "linhVuc": "Độ ẩm",
    "dichVu": "HC",
    "phamVi": "(10 ÷ 98) %RH",
    "mpelod": "0,09 %RH",
    "cmcMax": 2.3,
    "cmcDvt": "%RH",
    "quyTrinh": "ETV.MCH 01 (Phương tiện đo Độ ẩm không khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ ẩm - Trạm khí thải",
    "tenTA": "Hygrometer in emission air",
    "linhVuc": "Độ ẩm",
    "dichVu": "HC",
    "phamVi": "(10 ÷ 98) %RH",
    "mpelod": "0,09 %RH",
    "cmcMax": 2.3,
    "cmcDvt": "%RH",
    "quyTrinh": "ETV.MCH 01 (Phương tiện đo Độ ẩm không khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Nhiệt ẩm kế (Độ ẩm)",
    "tenTA": "Hygrometer",
    "linhVuc": "Độ ẩm",
    "dichVu": "HC",
    "phamVi": "(10 ÷ 98) %RH",
    "mpelod": "0,09 %RH",
    "cmcMax": 2.3,
    "cmcDvt": "%RH",
    "quyTrinh": "ETV.MCH 01 (Phương tiện đo Độ ẩm không khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị đặt mức áp suất",
    "tenTA": "Pressure Swich",
    "linhVuc": "Áp suất",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 600) bar",
    "mpelod": "0,5 %",
    "cmcMax": 0.2,
    "cmcDvt": "%",
    "quyTrinh": "ĐLVN 133:2004 (Thiết bị đặt mức áp suất - Quy trình hiệu chuẩn)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Áp suất",
    "tenTA": "Pressure gauge meter",
    "linhVuc": "Áp suất",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 600) bar",
    "mpelod": "1 %",
    "cmcMax": 0.18,
    "cmcDvt": "bar",
    "quyTrinh": "ĐLVN 76:2001 (Áp kế; áp kế lò xo; áp kế điện tử; baromet - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Baromet",
    "tenTA": "Barometer",
    "linhVuc": "Áp suất",
    "dichVu": "KĐ",
    "phamVi": "(1000 ÷ 1000) mBar",
    "mpelod": "đến 3 mBar",
    "cmcMax": 0.33,
    "cmcDvt": "mBar",
    "quyTrinh": "ĐLVN 76:2001 (Áp kế; áp kế lò xo; áp kế điện tử; baromet - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Áp kế kiểu lò xo",
    "tenTA": "Pressure gauge with elastic sensing element",
    "linhVuc": "Áp suất",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 600) bar",
    "mpelod": "1 %",
    "cmcMax": 0.18,
    "cmcDvt": "bar",
    "quyTrinh": "ĐLVN 76:2001 (Áp kế; áp kế lò xo; áp kế điện tử; baromet - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị chuyển đổi áp suất",
    "tenTA": "Pressure Transducer and Transmitter",
    "linhVuc": "Áp suất",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 600) bar",
    "mpelod": "0,5 %",
    "cmcMax": 0.18,
    "cmcDvt": "bar",
    "quyTrinh": "ĐLVN 112:2002 (Thiết bị chuyển đổi áp suất - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Dung dịch chuẩn Oxy hóa học (COD)",
    "tenTA": "COD standard solution",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 1500) mg/L",
    "mpelod": "5 %",
    "cmcMax": 5.1,
    "cmcDvt": "mg/L",
    "quyTrinh": "ETV.MTW 08 (Dung dịch chuẩn nhu cầu oxy hóa học (COD)  - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Dung dịch chuẩn Tổng chất rắn lơ lửng (TSS)",
    "tenTA": "Standard solutions of total suspended solid",
    "linhVuc": "Hoá lý (nước)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 2000) mg/L",
    "mpelod": "5 %",
    "cmcMax": 5.1,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MTW 02 (Dung dịch chuẩn - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Chênh áp suất",
    "tenTA": "Differential Pressure Gauge",
    "linhVuc": "Áp suất",
    "dichVu": "HC",
    "phamVi": "(0.4 ÷ 0.4) bar",
    "mpelod": "0,2 %",
    "cmcMax": 0.9,
    "cmcDvt": "mBar",
    "quyTrinh": "ETV.MCP 02 (Áp kế kiểu chênh áp - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo định vị bằng vệ tinh (GPS)",
    "tenTA": "Global Positioning System meter",
    "linhVuc": "Độ dài",
    "dichVu": "HC",
    "phamVi": "(8 ÷ 100) mm",
    "mpelod": "8,5 mm",
    "cmcMax": 8.5,
    "cmcDvt": "mm",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí SO₂ - Cầm tay",
    "tenTA": "Gas analyzers of SO₂ in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0.5) %V",
    "mpelod": "±2 %",
    "cmcMax": 0.7,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCA 02 (Phương tiện đo nồng độ các khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí O₂ - Cầm tay",
    "tenTA": "Gas analyzers of O₂ in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 25) %V",
    "mpelod": "4 %",
    "cmcMax": 0.6,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCA 02 (Phương tiện đo nồng độ các khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí CO - Cầm tay",
    "tenTA": "Gas analyzers of CO in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 1) %V",
    "mpelod": "±2 %",
    "cmcMax": 1.1,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCA 02 (Phương tiện đo nồng độ các khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí NO - Cầm tay",
    "tenTA": "Gas analyzers of NO in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0.5) %V",
    "mpelod": "±4 %",
    "cmcMax": 1.0,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCA 02 (Phương tiện đo nồng độ các khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3;13",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ ồn",
    "tenTA": "Sound level meter",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "KĐ",
    "phamVi": "(30 ÷ 114) dB",
    "mpelod": "1",
    "cmcMax": 0.62,
    "cmcDvt": "dB",
    "quyTrinh": "ĐLVN 89:2010 (Phương tiện đo độ ồn - Quy trình kiểm định)",
    "nangLucCode": "1;2",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí SO₂ - Cầm tay",
    "tenTA": "Gas analyzers of SO₂ in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 0.5) %V",
    "mpelod": "± 5 %",
    "cmcMax": 0.7,
    "cmcDvt": "%",
    "quyTrinh": "ĐLVN 265:2016 (Phương tiện đo nồng độ SO2, CO2, CO, NOx trong không khí - Quy trình kiểm định)",
    "nangLucCode": "1;2;2",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí CO - Cầm tay",
    "tenTA": "Gas analyzers of CO in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 1) %V",
    "mpelod": "± 5 %",
    "cmcMax": 1.1,
    "cmcDvt": "%",
    "quyTrinh": "ĐLVN 265:2016 (Phương tiện đo nồng độ SO2, CO2, CO, NOx trong không khí - Quy trình kiểm định)",
    "nangLucCode": "1;2;2",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí NO - Cầm tay",
    "tenTA": "Gas analyzers of NO in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 0.5) %V",
    "mpelod": "± 5 %",
    "cmcMax": 1.0,
    "cmcDvt": "%",
    "quyTrinh": "ĐLVN 265:2016 (Phương tiện đo nồng độ SO2, CO2, CO, NOx trong không khí - Quy trình kiểm định)",
    "nangLucCode": "1;2;2",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí NO₂ - Cầm tay",
    "tenTA": "Gas analyzers of NO₂ in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 0.5) %V",
    "mpelod": "± 5 %",
    "cmcMax": 2.1,
    "cmcDvt": "%",
    "quyTrinh": "ĐLVN 265:2016 (Phương tiện đo nồng độ SO2, CO2, CO, NOx trong không khí - Quy trình kiểm định)",
    "nangLucCode": "1;2;2",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nồng độ khí CO₂ - Cầm tay",
    "tenTA": "Gas analyzers of CO2 in air",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 16) %V",
    "mpelod": "± 5 %",
    "cmcMax": 0.7,
    "cmcDvt": "%",
    "quyTrinh": "ĐLVN 265:2016 (Phương tiện đo nồng độ SO2, CO2, CO, NOx trong không khí - Quy trình kiểm định)",
    "nangLucCode": "1;2;2",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo lưu lượng nước đường ống kín",
    "tenTA": "Measurement equipment of flow in closed conduit",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 0) m³/h",
    "mpelod": "2,2 %",
    "cmcMax": 5.0,
    "cmcDvt": "%",
    "quyTrinh": "ETV. MTF 05 (Phương tiện đo lưu lượng nước (kênh kín, kênh hở) - Quy trình thử nghiệm)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Lượng mưa - Trạm khí",
    "tenTA": "Rainfall measuring Instrument",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 700) mm/h",
    "mpelod": "35 mm/h",
    "cmcMax": -1.0,
    "cmcDvt": "mm/h",
    "quyTrinh": "ETV.MVF 11 (Phương tiện đo lượng mưa - Quy trình kiểm định nhóm 1)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo mực nước",
    "tenTA": "Water level Instrument",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 80000) mm",
    "mpelod": "2 mm",
    "cmcMax": 2.0,
    "cmcDvt": "mm",
    "quyTrinh": "ETV.MVF 12 (Phương tiện đo mực nước - Quy trình kiểm định nhóm 1)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phòng sạch",
    "tenTA": "Clean room",
    "linhVuc": "Cơ học",
    "dichVu": "TN",
    "phamVi": "(0.5 ÷ 30) m/s",
    "mpelod": "6 %",
    "cmcMax": 0.3,
    "cmcDvt": "m/s",
    "quyTrinh": "ETV.MTMe 02 (Phòng sạch - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Tủ cấy vi sinh",
    "tenTA": "Biological safety cabinets",
    "linhVuc": "Cơ học",
    "dichVu": "TN",
    "phamVi": "(0.5 ÷ 30) m/s",
    "mpelod": "6 %",
    "cmcMax": 0.5,
    "cmcDvt": "m/s",
    "quyTrinh": "ETV.MTMe 01 (Tủ an toàn sinh học - Quy trình nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị hấp tiệt trùng",
    "tenTA": "Autoclaving equipment",
    "linhVuc": "Cơ học",
    "dichVu": "TN",
    "phamVi": "(121 ÷ 200) °C",
    "mpelod": "0,5 °C",
    "cmcMax": 0.5,
    "cmcDvt": "°C",
    "quyTrinh": "ETV. MTT 02 (Thiết bị hấp tiệt trùng - Quy trình thử nghiệm)",
    "nangLucCode": "7",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ ẩm không khí",
    "tenTA": "Hygrometer",
    "linhVuc": "Độ ẩm",
    "dichVu": "KĐ",
    "phamVi": "(5 ÷ 95) %RH",
    "mpelod": "± %RH",
    "cmcMax": 0.5,
    "cmcDvt": "%RH",
    "quyTrinh": "ĐLVN 359:2019 (Phương tiện đo nhiệt độ/ độ ẩm không khí - Quy trình kiểm định)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Quang phổ tử ngoại khả kiến (UV-Vis)",
    "tenTA": "UV/Vis Spectrophotometer",
    "linhVuc": "Quang học",
    "dichVu": "KĐ",
    "phamVi": "(200 ÷ 900) nm",
    "mpelod": "0,3 nm",
    "cmcMax": 0.22,
    "cmcDvt": "nm",
    "quyTrinh": "ĐLVN 372:2020 (Phương tiện đo quang phổ tử ngoại - khả kiến -  Quy trình kiểm định)",
    "nangLucCode": "1;2",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Quang phổ tử ngoại khả kiến (UV-Vis) (*)",
    "tenTA": "UV/Vis Spectrophotometer",
    "linhVuc": "Quang học",
    "dichVu": "KĐ",
    "phamVi": "(200 ÷ 900) nm",
    "mpelod": "± 0.3 nm",
    "cmcMax": 0.22,
    "cmcDvt": "nm",
    "quyTrinh": "ĐLVN 372:2020 (Phương tiện đo quang phổ tử ngoại - khả kiến - Quy trình kiểm định nhóm 1)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị nhận, truyền và quản lý dữ liệu",
    "tenTA": "Datalogger",
    "linhVuc": "Điện từ - Không điện",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 11) mV",
    "mpelod": "0,045 %",
    "cmcMax": 2.0,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MTE 01 (Thiết bị truyền nhận dữ liệu (datalogger) – Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Cường độ ánh sáng",
    "tenTA": "Photometry Meter",
    "linhVuc": "Quang học",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 99999) Lux",
    "mpelod": "",
    "cmcMax": 0.08,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCO 02 (Phương tiện đo cường độ ánh sáng - Quy trình hiệu chuẩn)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ ẩm - Trạm khí tượng",
    "tenTA": "Humidity measuring device - Meteorological station",
    "linhVuc": "Độ ẩm",
    "dichVu": "HC",
    "phamVi": "(10 ÷ 90) %RH",
    "mpelod": "",
    "cmcMax": 2.3,
    "cmcDvt": "%RH",
    "quyTrinh": "ETV.MCH 01 (Phương tiện đo Độ ẩm không khí - Quy trình hiệu chuẩn)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Cân kỹ thuật",
    "tenTA": "Technical balance",
    "linhVuc": "Khối lượng",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 9000) g",
    "mpelod": "",
    "cmcMax": 0.36,
    "cmcDvt": "g",
    "quyTrinh": "ETV.MCM 01 (Cân phân tích và cân kỹ thuật - Quy trình hiệu chuẩn)",
    "nangLucCode": "1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Cường độ ánh sáng",
    "tenTA": "Photometry Meter",
    "linhVuc": "Quang học",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 100000) Lux",
    "mpelod": "2 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo hàm lượng Bụi - Trạm khí thải",
    "tenTA": "Analyzer of Dust",
    "linhVuc": "Quang học",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 10000) mg/m³",
    "mpelod": "±8 %",
    "cmcMax": 0,
    "cmcDvt": "%",
    "quyTrinh": "ETV.MCO 04 (Phương tiện đo hàm lượng bụi trong khí thải – Quy trình hiệu chuẩn)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Điện áp một chiều",
    "tenTA": "DC voltage",
    "linhVuc": "Điện từ - Không điện",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mV",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mV",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Dòng điện một chiều",
    "tenTA": "Direct current measuring instrument",
    "linhVuc": "Điện từ - Không điện",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mA",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mA",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Dòng điện xoay chiều",
    "tenTA": "Alternating current",
    "linhVuc": "Điện từ - Không điện",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mA",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mA",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Điện trở",
    "tenTA": "Resistor",
    "linhVuc": "Điện từ - Không điện",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) KSD",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "KSD",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Hàm lượng bụi (TSP; PM₁₀; PM 2,5; PM₁)",
    "tenTA": "Analyzer of Dust",
    "linhVuc": "Quang học",
    "dichVu": "TN",
    "phamVi": "(0 ~ 10000) mg/m³",
    "mpelod": "10 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTA 02 (Phương tiện đo hàm lượng bụi (TSP; PM10; PM 2,5; PM1) - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Khí chuẩn CO",
    "tenTA": "Standard gases of CO",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 10000) ppm",
    "mpelod": "± 5 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTA 03 (Khí chuẩn - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Khí chuẩn NO",
    "tenTA": "Standard gases of NO",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 5000) ppm",
    "mpelod": "5 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTA 03 (Khí chuẩn - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Khí chuẩn NO₂",
    "tenTA": "Standard gases of NO2",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 1100) ppm",
    "mpelod": "5 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTA 03 (Khí chuẩn - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Khí chuẩn SO₂",
    "tenTA": "Standard gases of SO2",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 5000) ppm",
    "mpelod": "5 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTA 03 (Khí chuẩn - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Khí chuẩn O₂",
    "tenTA": "Standard gases of O₂",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 25) %V",
    "mpelod": "5 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTA 03 (Khí chuẩn - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Khí chuẩn THC",
    "tenTA": "Standard gases of THC",
    "linhVuc": "Hoá lý (khí)",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 40000) ppm",
    "mpelod": "5 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTA 03 (Khí chuẩn - Quy trình thử nghiệm)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Bộ quả cân cấp chính xác F1",
    "tenTA": "Weights of F1 classes",
    "linhVuc": "Khối lượng",
    "dichVu": "HC",
    "phamVi": "(1 ÷ 500) mg",
    "mpelod": "± F1",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Bộ quả cân cấp chính xác E2",
    "tenTA": "Weights of classes E2",
    "linhVuc": "Khối lượng",
    "dichVu": "HC",
    "phamVi": "(1 ÷ 200) mg",
    "mpelod": "1",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Tủ an toàn sinh học",
    "tenTA": "Biosafety Cabinet",
    "linhVuc": "Cơ học",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) %",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Áp suất - Trạm Khí tượng",
    "tenTA": "Pressure meter",
    "linhVuc": "Áp suất",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 1200) mBar",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Bình áp lực",
    "tenTA": "Pressure cylinders",
    "linhVuc": "Áp suất",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0.7) bar",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8;7;9;11",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo áp suất",
    "tenTA": "Pressure gauge",
    "linhVuc": "Áp suất",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) bar",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "6;8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Máy đo độ sạch của dầu, nhớt",
    "tenTA": "Machine for measuring the cleanliness of oil and lubricants",
    "linhVuc": "Áp suất",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) bar",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "bar",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thước kẹp",
    "tenTA": "Caliper",
    "linhVuc": "Độ dài",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) m",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "m",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8;7;9",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Đồng hồ so",
    "tenTA": "Odometer",
    "linhVuc": "Độ dài",
    "dichVu": "HC",
    "phamVi": "(0 ~ 100) mm",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thước cuộn (> 20m)",
    "tenTA": "Tapes",
    "linhVuc": "Độ dài",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 100) m",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "11;10;1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Căn mẫu",
    "tenTA": "Gauge blocks",
    "linhVuc": "Độ dài",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 1000) mm",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ rung",
    "tenTA": "Vibration meter",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "KĐ",
    "phamVi": "(30 ÷ 119) dB",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "dB",
    "quyTrinh": "ĐLVN 264:2014 (Phương tiện đo độ rung động - Quy trình kiểm định)",
    "nangLucCode": "8;7;9;11",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Độ ồn - NTP",
    "tenTA": "Sound level meter",
    "linhVuc": "Thời gian - Tần số",
    "dichVu": "KĐ",
    "phamVi": "(30 ÷ 140) dB",
    "mpelod": "± 0,1 dB",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ĐLVN 89:2010 (Phương tiện đo độ ồn - Quy trình kiểm định)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị đo Bức xạ mặt trời",
    "tenTA": "Solar Radiation measuring device",
    "linhVuc": "Phóng xạ",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) Lux",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "6;8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị đo phóng xạ Gamma",
    "tenTA": "Radiation measuring equipment",
    "linhVuc": "Phóng xạ",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) µS/cm",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị đo phóng xạ tia X",
    "tenTA": "X-ray radiation equipment",
    "linhVuc": "Phóng xạ",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 1000) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Thiết bị đo hoạt độ phóng xạ Alpha Beta (bề mặt)",
    "tenTA": "Alpha Beta radioactivity measuring device (surface)",
    "linhVuc": "Phóng xạ",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 1000) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Hiệu chỉnh, thử nghiệm phương tiện đo khí",
    "tenTA": "Testing of Gas analyzers",
    "linhVuc": "Giải ngân",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 0) mg/m³",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTA 01 (Phương tiện đo nồng độ các thông số trong không khí - Quy trình thử nghiệm)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Hiệu chỉnh, thử nghiệm phương tiện đo nhiệt độ",
    "tenTA": "Testing of Temprature",
    "linhVuc": "Giải ngân",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 1000) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV. MTT 01 (Phương tiện đo nhiệt độ môi trường nước - Quy trình thử nghiệm)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Hiệu chỉnh, thử nghiệm phương tiện đo lưu lượng",
    "tenTA": "LL",
    "linhVuc": "Giải ngân",
    "dichVu": "TN",
    "phamVi": "(0 ÷ 1000) mL/min",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MTF 04 (Thiết bị đo lưu lượng khí thải - Quy trình thử nghiệm)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo lưu lượng nước đường ống kín (DN 50)",
    "tenTA": "Measurement equipment of flow in closed conduit",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ~ 100) m³/h",
    "mpelod": "± (2; 5) %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ĐLVN 17 : 2017 (Đồng hồ đo nước - Quy trình kiểm định)",
    "nangLucCode": "-1;8;11;11",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo lưu lượng nước đường ống kín (DN 80)",
    "tenTA": "Measurement equipment of flow in closed conduit",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 200) m³/h",
    "mpelod": "± (2; 5) %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ĐLVN 17 : 2017 (Đồng hồ đo nước - Quy trình kiểm định)",
    "nangLucCode": "8;11;11",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo lưu lượng nước đường ống kín (＜DN 100)",
    "tenTA": "Measurement equipment of flow in closed conduit",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ~ 100) m³/h",
    "mpelod": "± (2; 5) %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ĐLVN 17 : 2017 (Đồng hồ đo nước - Quy trình kiểm định)",
    "nangLucCode": "-1;8;11;11",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo lưu lượng nước đường ống kín (< DN 150)",
    "tenTA": "Measurement equipment of flow in closed conduit",
    "linhVuc": "Dung tích - Lưu lượng",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 150) m³/h",
    "mpelod": "± (2; 5) %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ĐLVN 17 : 2017 (Đồng hồ đo nước - Quy trình kiểm định)",
    "nangLucCode": "8;11;11",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Bộ quả cân cấp chính xác E2",
    "tenTA": "Weights of classes E2",
    "linhVuc": "Khối lượng",
    "dichVu": "TN",
    "phamVi": "(1 ÷ 200) mg",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (TN) (Quy trình thử nghiệm - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo nhiệt độ, độ ẩm",
    "tenTA": "",
    "linhVuc": "Độ ẩm",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 0) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "°C",
    "quyTrinh": "ĐLVN 359:2019 (Phương tiện đo nhiệt độ/ độ ẩm không khí - Quy trình kiểm định)",
    "nangLucCode": "8;11;1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo hàm lượng Bụi - Trạm khí thải",
    "tenTA": "Analyzer of Dust",
    "linhVuc": "Quang học",
    "dichVu": "KĐ",
    "phamVi": "(0 ~ 10000) mg/m³",
    "mpelod": "8 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MVO 04 (Phương tiện đo hàm lượng Bụi (TSP; TP; PM; PM10; PM2.5; PM1.0) - Quy trình kiểm định nhóm 1)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Hàm lượng bụi (TSP; PM₁₀; PM 2,5; PM₁)",
    "tenTA": "Analyzer of Dust",
    "linhVuc": "Quang học",
    "dichVu": "KĐ",
    "phamVi": "(0 ~ 10000) mg/m³",
    "mpelod": "10 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MVO 03 (Phương tiện đo hàm lượng Bụi (TSP; TP; PM; PM10; PM2.5; PM1.0) - Quy trình kiểm định nhóm 1)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo Cường độ ánh sáng (Độ rọi)",
    "tenTA": "Illuminance meter",
    "linhVuc": "Quang học",
    "dichVu": "KĐ",
    "phamVi": "(10 ÷ 20000) Lux",
    "mpelod": "± 1 %",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ĐLVN 257 : 2014 (Phương tiện đo độ rọi - Quy trình kiểm định)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Test định mức KTKT 3",
    "tenTA": "Test DMKTKT 3",
    "linhVuc": "Không lĩnh vực",
    "dichVu": "HC",
    "phamVi": "(-2 ÷ 16) pH",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "pH",
    "quyTrinh": "ETV.MCW 01 (Phương tiện đo pH - Quy trình hiệu chuẩn)",
    "nangLucCode": "6",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Test định mức KTKT 4",
    "tenTA": "Test DMKTKT 1",
    "linhVuc": "Không lĩnh vực",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "mg/L",
    "quyTrinh": "ETV.MCW 01 (Phương tiện đo pH - Quy trình hiệu chuẩn)",
    "nangLucCode": "-1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Test định mức KTKT 5",
    "tenTA": "Test DMKTKT 1",
    "linhVuc": "Không lĩnh vực",
    "dichVu": "HC",
    "phamVi": "(-2 ÷ 16) pH",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "ETV.MCW 01 (Phương tiện đo pH - Quy trình hiệu chuẩn)",
    "nangLucCode": "-1;3",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Máy xét nghiệm sinh hóa",
    "tenTA": "Biochemical testing machine",
    "linhVuc": "Y tế",
    "dichVu": "HC",
    "phamVi": "(0 ÷ 0) mg/L",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (HC) (Quy trình hiệu chuẩn - Nhà thầu phụ)",
    "nangLucCode": "1",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Bộ quả cân cấp chính xác F1",
    "tenTA": "Weights of F1 classes",
    "linhVuc": "Điện từ - Không điện",
    "dichVu": "TN",
    "phamVi": "(1 ÷ 500) mg",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "",
    "quyTrinh": "NTP (TN) (Quy trình thử nghiệm - Nhà thầu phụ)",
    "nangLucCode": "8",
    "trangThaiPTD": "ĐN LĐP duyệt"
  },
  {
    "ten": "Phương tiện đo GSOT TEST 07062023",
    "tenTA": "Phương tiện đo GSOT TEST 07062023",
    "linhVuc": "Lĩnh vực test",
    "dichVu": "KĐ",
    "phamVi": "(0 ÷ 2) °C",
    "mpelod": "±",
    "cmcMax": 0,
    "cmcDvt": "°C",
    "quyTrinh": "ĐLVN 259 : 2015 (Cân treo móc cẩu - Quy trình kiểm định)",
    "nangLucCode": "7; 9; 10",
    "trangThaiPTD": "ĐN LĐP duyệt"
  }
];
