-- CreateEnum
CREATE TYPE "AIDataBoundary" AS ENUM ('NO_EXTERNAL_TRANSFER', 'EXTERNAL_WITH_COMMITMENT', 'EXTERNAL_NO_COMMITMENT');

-- AlterTable
ALTER TABLE "AIPlatform" ADD COLUMN     "dataBoundary" "AIDataBoundary" NOT NULL DEFAULT 'EXTERNAL_NO_COMMITMENT',
ADD COLUMN     "dataBoundaryRef" TEXT;
